### ISSUE TITLE
Impossible to build since 5.1.9

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#1983]
Hello,

I'm facing a several problem. I just updated to 5.1.9 and since then it is impossible to run the build command on node. It fails in all my plugin repositories, and it worked on 5.1.8 so I'm pretty sure it is not my fault.

Here is the error log:

```
Boot log:
  Startup task: load-modules
  Startup task: info after: load-modules before: startup
  Startup task: startup after: load-modules
  Startup task: story after: startup
  Startup task: commands platforms: node after: story
Executing command: build
Executing command: rendertiddler ReadMe readme.md text/html
Executing command: rendertiddler License license.md text/html
Executing command: savetiddler $:/favicon.ico favicon.ico

$:/core/modules/commands/savetiddler.js:36
                type = tiddler.fields.type || "text/vnd.tiddlywiki",
                              ^
TypeError: Cannot read property 'fields' of undefined
    at Command.execute ($:/core/modules/commands/savetiddler.js:36:17)
    at Commander.executeNextCommand ($:/core/modules/commander.js:97:14)
    at null.callback ($:/core/modules/commander.js:94:13)
    at $:/core/modules/commands/rendertiddler.js:38:8
    at Object.oncomplete (fs.js:107:15)
```

This is very bad because it also breaks all the builds that I have setup at Travis-CI, so I'm unable to update/publish anything.

**Comment by danielo515** [comment]
Sorry, my bad, I think I'm just doing something wrong. I was building on other repos with the wrong command. I have updated the error log.

**Comment by danielo515** [comment]
Ok, I have isolated the issue at a json file that looks like this:

```
{
  "backspace" : "8",
  "tab" : "9",
  "enter" : "13",
  "shift" : "16",
  "ctrl" : "17",
  "alt" : "18",
  "pause_break" : "19",
  "caps_lock" : "20",
  "escape" : "27",
  "page_up" : "33",
  "page down" : "34",
  "end" : "35",
  "home" : "36",
  "left_arrow" : "37",
  "up_arrow" : "38",
  "right_arrow" : "39",
  "down_arrow" : "40",
  "insert" : "45",
  "delete" : "46",
  "0" : "48",
  "1" : "49",
  "2" : "50",
  "3" : "51",
  "4" : "52",
  "5" : "53",
  "6" : "54",
  "7" : "55",
  "8" : "56",
  "9" : "57",
  "a" : "65",
  "b" : "66",
  "c" : "67",
  "d" : "68",
  "e" : "69",
  "f" : "70",
  "g" : "71",
  "h" : "72",
  "i" : "73",
  "j" : "74",
  "k" : "75",
  "l" : "76",
  "m" : "77",
  "n" : "78",
  "o" : "79",
  "p" : "80",
  "q" : "81",
  "r" : "82",
  "s" : "83",
  "t" : "84",
  "u" : "85",
  "v" : "86",
  "w" : "87",
  "x" : "88",
  "y" : "89",
  "z" : "90",
  "left_window key" : "91",
  "right_window key" : "92",
  "select_key" : "93",
  "numpad 0" : "96",
  "numpad 1" : "97",
  "numpad 2" : "98",
  "numpad 3" : "99",
  "numpad 4" : "100",
  "numpad 5" : "101",
  "numpad 6" : "102",
  "numpad 7" : "103",
  "numpad 8" : "104",
  "numpad 9" : "105",
  "multiply" : "106",
  "add" : "107",
  "subtract" : "109",
  "decimal point" : "110",
  "divide" : "111",
  "f1" : "112",
  "f2" : "113",
  "f3" : "114",
  "f4" : "115",
  "f5" : "116",
  "f6" : "117",
  "f7" : "118",
  "f8" : "119",
  "f9" : "120",
  "f10" : "121",
  "f11" : "122",
  "f12" : "123",
  "num_lock" : "144",
  "scroll_lock" : "145",
  "semi_colon" : "186",
  "equal_sign" : "187",
  "comma" : "188",
  "dash" : "189",
  "period" : "190",
  "forward_slash" : "191",
  "grave_accent" : "192",
  "open_bracket" : "219",
  "backslash" : "220",
  "closebracket" : "221",
  "single_quote" : "222"
 }
```

I don't understand what is the problem, it is correctly formatted.

**Comment by danielo515** [comment]
@Jermolene , do you see any problem with the mentioned file?

**Comment by tobibeer** [comment]
http://jsonlint.com says you're good

**Comment by Jermolene** [comment]
Hi @danielo515 did you resolve this issue? The JSON file looks fine, so I think we'll need some more context to debug the problem further.

**Comment by danielo515** [comment]
The issue is that even importing it as a tiddler (with all the required fields and type) and I'm still getting the same errors

**Comment by Jermolene** [comment]
Hi @danielo515 so do you have a .meta file for it? How are you using it? Can you point me at the code?

**Comment by danielo515** [comment]
Hello @Jermolene ,

I don't have a meta file for it, I tried adding the fields at the beginning of the tiddler, like any other .tid file. Maybe it only works with meta files? I am tempted to just create a tiddler and paste the content inside and set the type to application json.

**Comment by Jermolene** [comment]
@danielo515 if you try to import/load a JSON file without a .meta file then TiddlyWiki expects it to be a JSON file consisting of an array called "tiddlers", just as you see if you do a JSON export.

If you want to format the fields of the JSON file like a .tid file then you have to actually make it be a .tid file, with the right extension.

**Comment by Jermolene** [comment]
I'm a bit confused though, because you said that this used to work under 5.1.9?

**Comment by danielo515** [comment]
Hello Jeremy, 

This has never worked on 5.1.9
I tried creating the json file as a tid file manually an it did not worked. What I have done is create a tiddler on TW, put the content, set the content type and export it as `.tid` file. That way it worked.

Regards

**Comment by danielo515** [comment]
Sorry, I have closed the issue to fast. 

The problem persists. Here is the error log:

```
Boot log:
  Startup task: load-modules
  Startup task: info after: load-modules before: startup
  Startup task: startup after: load-modules
  Startup task: story after: startup
  Startup task: commands platforms: node after: story
Executing command: build
Executing command: rendertiddler ReadMe readme.md text/html
Executing command: rendertiddler License license.md text/html
Executing command: savetiddler $:/favicon.ico favicon.ico

$:/core/modules/commands/savetiddler.js:36
                type = tiddler.fields.type || "text/vnd.tiddlywiki",
                              ^
TypeError: Cannot read property 'fields' of undefined
    at Command.execute ($:/core/modules/commands/savetiddler.js:36:17)
    at Commander.executeNextCommand ($:/core/modules/commander.js:97:14)
    at null.callback ($:/core/modules/commander.js:94:13)
    at $:/core/modules/commands/rendertiddler.js:38:8
    at Object.oncomplete (fs.js:107:15)
```

And here is the `tid` file : 


```
created: 20151005072428241
creator: pene
modified: 20151005072636302
modifier: pene
tags: 
title: $:/plugins/danielo/keyboardSnippets/KEYCODES
type: application/json

{
  "backspace" : "8",
  "tab" : "9",
  "enter" : "13",
  "shift" : "16",
  "ctrl" : "17",
  "alt" : "18",
  "pause_break" : "19",
  "caps_lock" : "20",
  "escape" : "27",
  "page_up" : "33",
  "page down" : "34",
  "end" : "35",
  "home" : "36",
  "left_arrow" : "37",
  "up_arrow" : "38",
  "right_arrow" : "39",
  "down_arrow" : "40",
  "insert" : "45",
  "delete" : "46",
  "0" : "48",
  "1" : "49",
  "2" : "50",
  "3" : "51",
  "4" : "52",
  "5" : "53",
  "6" : "54",
  "7" : "55",
  "8" : "56",
  "9" : "57",
  "a" : "65",
  "b" : "66",
  "c" : "67",
  "d" : "68",
  "e" : "69",
  "f" : "70",
  "g" : "71",
  "h" : "72",
  "i" : "73",
  "j" : "74",
  "k" : "75",
  "l" : "76",
  "m" : "77",
  "n" : "78",
  "o" : "79",
  "p" : "80",
  "q" : "81",
  "r" : "82",
  "s" : "83",
  "t" : "84",
  "u" : "85",
  "v" : "86",
  "w" : "87",
  "x" : "88",
  "y" : "89",
  "z" : "90",
  "left_window key" : "91",
  "right_window key" : "92",
  "select_key" : "93",
  "numpad 0" : "96",
  "numpad 1" : "97",
  "numpad 2" : "98",
  "numpad 3" : "99",
  "numpad 4" : "100",
  "numpad 5" : "101",
  "numpad 6" : "102",
  "numpad 7" : "103",
  "numpad 8" : "104",
  "numpad 9" : "105",
  "multiply" : "106",
  "add" : "107",
  "subtract" : "109",
  "decimal point" : "110",
  "divide" : "111",
  "f1" : "112",
  "f2" : "113",
  "f3" : "114",
  "f4" : "115",
  "f5" : "116",
  "f6" : "117",
  "f7" : "118",
  "f8" : "119",
  "f9" : "120",
  "f10" : "121",
  "f11" : "122",
  "f12" : "123",
  "num_lock" : "144",
  "scroll_lock" : "145",
  "semi_colon" : "186",
  "equal_sign" : "187",
  "comma" : "188",
  "dash" : "189",
  "period" : "190",
  "forward_slash" : "191",
  "grave_accent" : "192",
  "open_bracket" : "219",
  "backslash" : "220",
  "closebracket" : "221",
  "single_quote" : "222"
 }
```

**Comment by danielo515** [comment]
To be 100% clear, there is no problem booting the wiki in node. It's just when I try to build the index file when it fails.

**Comment by Jermolene** [comment]
It looks as though you've got a "savetiddler" command that is saving the favicon in the tiddler `$:/favicon.ico" into the file `favicon.ico`. Have you in fact got a favicon tiddler called `$:/favicon.ico`? If not, you should either create/import one, or remove that command from the build.

**Comment by danielo515** [comment]
Hello Jeremy, that was the problem, thank you :+1: 

But I'm still not understanding why just having a .json file on the tiddlers folder, no mater how bad formatted it is breaks the build. I just expect to not be included, not to breaking the entire flow.

**Comment by Jermolene** [comment]
Hi @danielo515 yes, it's not very helpful that it crashes; I'd accept a pull request to improve the mode of failure.

**Comment by danielo515** [comment]
Hello @Jermolene 
Should we close this ticket and open another explaining the issue better?
Regards

**Comment by Jermolene** [comment]
Yes, that makes sense.

**Comment by pmario** [comment]
I think we have a PR. see: "fixes a problem with the --savetiddler command, #555 " .. but I have to have a closer look again.
