### ISSUE TITLE
Error: TiddlyWiki under NW.js

### ISSUE THREAD

**Issue by sinky** [Jermolene/TiddlyWiki5#3023]
Hi,
I don't want to use TiddlyDesktop because i don't need the multi-wiki support. I wish the exe should open the wiki direct after start.

I'am trying to use TiddlyWiki with a fresh NW.js. Just how described here: https://tiddlywiki.com/dev/static/TiddlyWiki%2520on%2520NW.js.html

But it starts with the following error in the Dev-Console.

> Uncaught Error: Cannot find module './sjcl.js'
    at Function.Module._resolveFilename (module.js:567:15)
    at Function.Module._load (module.js:492:25)
    at Module.require (module.js:610:17)
    at require (internal/module.js:11:18)
    at self.require (<anonymous>:11:26)

If i download sjcl.js an save it beside the index.html a new error is thrown

> Uncaught ReferenceError: module is not defined
    at Object.$tw.boot.startup (index.html:10615)
    at index.html:10880
    at Object.$tw.boot.decryptEncryptedTiddlers (index.html:10160)
    at Object.$tw.boot.boot (index.html:10878)
    at _boot (index.html:10887)
    at index.html:10897

**Comment by pmario** [comment]
@Jermolene -- This is TiddlyDesktop. -- Do you know these type of problems?

**Comment by Jermolene** [comment]
Thank you @pmario
