### ISSUE TITLE
How to run on heroku? (how to run via 'node tiddlywiki')

### ISSUE THREAD

**Issue by stefek99** [Jermolene/TiddlyWiki5#340]
Hi,

Someone has already asked on Dev mailing list and for couple of months there was no answer: https://groups.google.com/forum/#!topic/TiddlyWikiDev/q9Aga3tEdL0 _(I actually resurfaced this post)_

I read the instructions here - http://tiddlywiki.com/#Scripts%20for%20TiddlyWiki%20on%20Node.js and here - http://tiddlywiki.com/#TiddlyWiki%20for%20Developers 

(linking to fragments does not work, created separate issue for that: https://github.com/Jermolene/TiddlyWiki5/issues/338 )
### What I tried:

When I look at **package.json** I see:

```
  "bin": {
    "tiddlywiki": "./tiddlywiki.js"
  }
```

When I try to run via **node tiddlywiki.js** on localhost I get:

```
fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/__BLAH__/TiddlyWiki5/plugins/tiddlywiki/plugin.info'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
```

I know that I should run via `tiddlywiki --server` but I tried via **node tiddlywiki.js** as it traditional way of running node apps and it will be required for heroku: https://devcenter.heroku.com/articles/getting-started-with-nodejs

```
echo "web: node tiddlywiki.js -server" >> Procfile
git add Procfile
git commit -m "adding Procfile as it is required by heroku"

heroku create
git push heroku master
heroku ps:scale web=1
heroku open
heroku logs
```

I believe it is pretty much the same issue:

```
2014-01-12T23:41:07+00:00 heroku[slug-compiler]: Slug compilation finished
2014-01-12T23:41:07.332698+00:00 heroku[api]: Deploy 861f272 by mstefanow@gmail.com
2014-01-12T23:41:07.362476+00:00 heroku[api]: Release v4 created by mstefanow@gmail.com
2014-01-12T23:41:17.753789+00:00 heroku[api]: Scale to web=1 by mstefanow@gmail.com
2014-01-12T23:41:20.064154+00:00 heroku[web.1]: Starting process with command `node tiddlywiki.js -server`
2014-01-12T23:41:23.493556+00:00 app[web.1]:
2014-01-12T23:41:23.494211+00:00 app[web.1]: fs.js:642
2014-01-12T23:41:23.497965+00:00 app[web.1]:     at Object.fs.mkdirSync (fs.js:642:18)
2014-01-12T23:41:23.497965+00:00 app[web.1]:     at Object.$tw.modules.forEachModuleOfType (/app/boot/boot.js:654:12)
2014-01-12T23:41:23.497965+00:00 app[web.1]: Error: ENOENT, no such file or directory '/app/-server/tiddlers'
2014-01-12T23:41:23.497965+00:00 app[web.1]:     at new FileSystemAdaptor ($:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:48:6)
2014-01-12T23:41:23.497965+00:00 app[web.1]:     at /app/boot/boot.js:655:3
2014-01-12T23:41:23.497965+00:00 app[web.1]:     at Object.$tw.utils.each (/app/boot/boot.js:92:6)
2014-01-12T23:41:23.497965+00:00 app[web.1]:     at new Syncer ($:/core/modules/syncer.js:24:14)
2014-01-12T23:41:23.497965+00:00 app[web.1]:     at /app/boot/boot.js:1460:11
2014-01-12T23:41:23.497965+00:00 app[web.1]:     at Object.exports.startup ($:/core/modules/startup.js:35:15)
2014-01-12T23:41:23.497965+00:00 app[web.1]:     at $:/core/modules/syncer.js:26:23
2014-01-12T23:41:23.498164+00:00 app[web.1]:     at /app/boot/boot.js:655:3
2014-01-12T23:41:23.494624+00:00 app[web.1]:   return binding.mkdir(pathModule._makeLong(path),
```

Any hints / suggestions / pointers?

(thank you)

PS. My feeling is that for better developer experience and wider adoption this may help...

**Comment by panicsteve** [comment]
Heroku dynos have ephemeral filesystems, so even if you can get it to run, any content that gets written to the filesystem (ie; your tiddlers) will vanish when the dyno is stopped, restarted, etc.

Source: https://devcenter.heroku.com/articles/dynos#isolation-and-security

**Comment by bradoyler** [comment]
@stefek99 have you got this working on Heroku?

**Comment by nome** [comment]
Maybe this kind of setup could be simplified by relaxing the wiki folder definition? Instead of requiring all subfolders of ./plugins to be plugin folders, tiddlywiki could scan recursive for any folders containing a `plugin.info`.

**Comment by pmario** [comment]
The usual way to run TW with `node tiddlywiki.js ... ` needs the following steps.

`npm install tiddlywiki` ... which creates a `.node_modules` path inthe current directoy and installs TW
`node ./node_modules/tiddlywiki/tiddlywiki.js --version` ... checks the TW version and shows if the installation worked.
` node .\node_modules\tiddlywiki\tiddlywiki.js ./wiki --init server` ... creates a `wiki` folder in the current directory and installs the `tiddlywiki.info` file with server settings into the wiki folder
`node .\node_modules\tiddlywiki\tiddlywiki.js ./wiki --listen` ... starts the server with with `localhost` and **no security**

All tiddlers will be saved to the `tiddlers` directory.

More commands can be found at: https://tiddlywiki.com/#Commands and https://tiddlywiki.com/#Plugins if plugins are needed.

This workflow should have worked 9 years ago. BUT I do not know if the filesystem at heroky is persistent.

----------

@Jermolene ... IMO this issue is 9 years old and should be tried with the latest heroku version. 

IMO this issue should be closed.
