### ISSUE TITLE
TW exits with error "has no method 'from'"

### ISSUE THREAD

**Issue by tjerry** [Jermolene/TiddlyWiki5#3933]
I have just updated Node and TW on QNAP NAS.

Node - node_legacy v0.10.48-2
TW - 5.1.19

When I try to start TW, I get this error:

```javascript
  $:/core/modules/utils/utils.js:733
 return Buffer.from(string64,"base64").toString();
                               ^
 TypeError: Object function Buffer(subject, encoding, offset) {
   if (!(this instanceof Buffer)) {
     return new Buffer(subject, encoding, offset);
   }
 
 [...]
 
   SlowBuffer.makeFastBuffer(this.parent, this, this.offset, this.length);
 } has no method 'from'
     at exports.base64Decode ($:/core/modules/utils/utils.js:733:17)
     at BasicAuthenticator.authenticateRequest ($:/core/modules/server/authenticators/basic.js:70:20)
     at Server.requestHandler ($:/core/modules/server/server.js:174:30)
     at Server.emit (events.js:98:17)
     at HTTPParser.parser.onIncoming (http.js:2171:12)
     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:152:23)
     at Socket.socket.ondata (http.js:2029:22)
     at TCP.onread (net.js:528:27
```

What would be the best way to solve this?

**Comment by pmario** [comment]
Is it possible, that you use a newer version of node?

**Comment by tjerry** [comment]
Ah, yes.
I installed node v8 and node-npm v8 and there is no problem now.
I don't know how I missed the v8 earlier.
Thanks.

**Comment by pmario** [comment]
cool ... can you close the issue please?
