### ISSUE TITLE
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["WWW-Authenticate"]

### ISSUE THREAD

**Issue by paulojeronimo** [Jermolene/TiddlyWiki5#4236]
When I run tiddlywiki 5.1.20 via yarn with the following script:

```
"wiki-listen": "tiddlywiki wiki --listen credentials=users.csv \"readers=(anon)\" writers=\"(authenticated)\"",
```

I receive this error when I try to authenticate via http://localhost:8080/login-basic:

```
_http_outgoing.js:458
    throw new ERR_INVALID_CHAR('header content', name);
    ^

TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["WWW-Authenticate"]
    at storeHeader (_http_outgoing.js:411:5)
    at processHeader (_http_outgoing.js:406:3)
    at ServerResponse._storeHeader (_http_outgoing.js:311:11)
    at ServerResponse.writeHead (_http_server.js:304:8)
    at BasicAuthenticator.authenticateRequest ($:/core/modules/server/authenticators/basic.js:84:12)
    at Server.requestHandler ($:/core/modules/server/server.js:177:30)
    at Server.emit (events.js:203:13)
    at parserOnIncoming (_http_server.js:735:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
error Command failed with exit code 1.
```

**Comment by Jermolene** [comment]
Hi @paulojeronimo I'm having trouble duplicating the problem. What version of Node.js are you using? Is there any proxying going on?

**Comment by paulojeronimo** [comment]
Hi @Jermolene . This error occurs in macOS environment using the following Node.js version:
```
$ node --version
v12.8.0
```
Today I´ll try to reproduce the same situation on Arch Linux later. I'll let you know the results here.

**Comment by Jermolene** [comment]
Hi @paulojeronimo hilariously, I just ran into this same problem, and so googled the error message, and ended up back here!

The issue for me was that I had a line break in my $:/SiteTitle; removing the line break fixes  things. It's a bug, though, and I'll fix it properly as soon as I can.
