### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of null

### ISSUE THREAD

**Issue by dorneanu** [Jermolene/TiddlyWiki5#4241]
Hi! Recently I've installed some new widgets/plugins and then the next day I tried to fire up TW again:

```
tiddlywiki ᐅ tiddlywiki wiki --listen port=8181 host=0.0.0.0 csrf-disable=yes
$:/core/modules/wiki.js:263
        if(this.getTiddlerText(TIMESTAMP_DISABLE_TITLE,"").toLowerCase() !== "yes") {
                                                          ^

TypeError: Cannot read property 'toLowerCase' of null
    at $tw.Wiki.exports.getModificationFields ($:/core/modules/wiki.js:263:52)
    at openStartupTiddlers ($:/core/modules/startup/story.js:151:87)
    at Object.exports.startup ($:/core/modules/startup/story.js:39:2)
    at Object.$tw.boot.executeNextStartupTask (/usr/lib/node_modules/tiddlywiki/boot/boot.js:2350:10)
    at Object.$tw.boot.executeNextStartupTask (/usr/lib/node_modules/tiddlywiki/boot/boot.js:2354:21)
    at Object.$tw.boot.executeNextStartupTask (/usr/lib/node_modules/tiddlywiki/boot/boot.js:2354:21)
    at Object.$tw.boot.executeNextStartupTask (/usr/lib/node_modules/tiddlywiki/boot/boot.js:2354:21)
    at Object.$tw.boot.startup (/usr/lib/node_modules/tiddlywiki/boot/boot.js:2307:11)
    at /usr/lib/node_modules/tiddlywiki/boot/boot.js:2460:12
    at Object.$tw.boot.decryptEncryptedTiddlers (/usr/lib/node_modules/tiddlywiki/boot/boot.js:1703:2)
```

What can I do about this? Thanks in advance. 

BR,
Victor

**Comment by KhalfaniWadlington** [comment]
I had a similar issue
```
$ tiddlywiki --listen port=8888
$:/core/modules/wiki.js:263
	if(this.getTiddlerText(TIMESTAMP_DISABLE_TITLE,"").toLowerCase() !== "yes") {
	                                                  ^

TypeError: Cannot read property 'toLowerCase' of null
    at $tw.Wiki.exports.getModificationFields ($:/core/modules/wiki.js:263:52)
    at openStartupTiddlers ($:/core/modules/startup/story.js:151:87)
    at Object.exports.startup ($:/core/modules/startup/story.js:39:2)
    at Object.$tw.boot.executeNextStartupTask (/usr/lib/node_modules/tiddlywiki/boot/boot.js:2350:10)
    at Object.$tw.boot.executeNextStartupTask (/usr/lib/node_modules/tiddlywiki/boot/boot.js:2354:21)
    at Object.$tw.boot.executeNextStartupTask (/usr/lib/node_modules/tiddlywiki/boot/boot.js:2354:21)
    at Object.$tw.boot.executeNextStartupTask (/usr/lib/node_modules/tiddlywiki/boot/boot.js:2354:21)
    at Object.$tw.boot.startup (/usr/lib/node_modules/tiddlywiki/boot/boot.js:2307:11)
    at /usr/lib/node_modules/tiddlywiki/boot/boot.js:2460:12
    at Object.$tw.boot.decryptEncryptedTiddlers (/usr/lib/node_modules/tiddlywiki/boot/boot.js:1703:2)
```
I started guessing with tiddlers were causing the issue by moving the tiddlers that start with $ out the directory one by one.


I eventually deleted this tiddler `$__config_TimestampDisable.tid`  which contained 
```
$  cat \$__config_TimestampDisable.tid
created: 20190830020251402
creator: khalfani
modified: 20200111014217546
modifier: khalfani
title: $:/config/TimestampDisable
type: text/vnd.tiddlywiki
```

I have no idea why this fixed it lol.

**Comment by pmario** [comment]
`tiddlywiki --listen port=8888` ... this command is wrong. it needs to be 

```
tiddlywiki ./path/to/edition --listen port=8888
```

**Comment by pmario** [comment]
@Jermolene 

There is a problem here: https://github.com/Jermolene/TiddlyWiki5/blob/7795ed92300b6ed73062363484eff68de4c141f6/core/modules/wiki.js#L1242 if lazyloading is active.  `this.getTiddlerText()` returns `null`. If that happens, it causes an error. ... So there is a bug.

**Comment by MedicoreV8** [comment]
This is the only thread I could find on google.
I have the exact same problem running TW5 on Node.js.

Lazy loading is not active. I have several Tiddlers and I'm trying to start TW5 with:
`/usr/local/bin/tiddlywiki /root/wiki --listen "readers=(anon)" writers=xxxx username=yyyy password=zzzz host=0.0.0.0 port=80`

`$:/core/modules/wiki.js:263
        if(this.getTiddlerText(TIMESTAMP_DISABLE_TITLE,"").toLowerCase() !== "yes") {
                                                          ^

TypeError: Cannot read property 'toLowerCase' of null
    at $tw.Wiki.exports.getModificationFields ($:/core/modules/wiki.js:263:52)
    at openStartupTiddlers ($:/core/modules/startup/story.js:151:87)
    at Object.exports.startup ($:/core/modules/startup/story.js:39:2)
    at Object.$tw.boot.executeNextStartupTask (/usr/local/lib/node_modules/tiddlywiki/boot/boot.js:2350:10)
    at Object.$tw.boot.executeNextStartupTask (/usr/local/lib/node_modules/tiddlywiki/boot/boot.js:2354:21)
    at Object.$tw.boot.executeNextStartupTask (/usr/local/lib/node_modules/tiddlywiki/boot/boot.js:2354:21)
    at Object.$tw.boot.executeNextStartupTask (/usr/local/lib/node_modules/tiddlywiki/boot/boot.js:2354:21)
    at Object.$tw.boot.startup (/usr/local/lib/node_modules/tiddlywiki/boot/boot.js:2307:11)
    at /usr/local/lib/node_modules/tiddlywiki/boot/boot.js:2460:12
    at Object.$tw.boot.decryptEncryptedTiddlers (/usr/local/lib/node_modules/tiddlywiki/boot/boot.js:1703:2)
`
