### ISSUE TITLE
editions/test/ shows runtime error with 5.1.21

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#4390]
@Jermolene 

I did checkout tag: v5.1.21 and wanted to run the tests. -> error

IMO tests should pass if new version is published. 

I wanted to add some `enlist filter` tests, but can't run the existing tests. 

```
TypeError: this.print_ is not a function
    at jasmineNode.TerminalVerboseReporter.printLine_ ($:/plugins/tiddlywiki/jasmine/reporter.js:191:12)
    at jasmineNode.TerminalVerboseReporter.reportRunnerResults ($:/plugins/tiddlywiki/jasmine/reporter.js:224:14)
    at jasmine.MultiReporter.reportRunnerResults ($:/plugins/tiddlywiki/jasmine/jasmine.js:1789:39)
    at jasmine.Runner.finishCallback ($:/plugins/tiddlywiki/jasmine/jasmine.js:2161:21)
    at jasmine.Queue.onComplete ($:/plugins/tiddlywiki/jasmine/jasmine.js:2145:10)
    at jasmine.Queue.next_ ($:/plugins/tiddlywiki/jasmine/jasmine.js:2107:14)
    at onComplete ($:/plugins/tiddlywiki/jasmine/jasmine.js:2093:18)
    at jasmine.Suite.finish ($:/plugins/tiddlywiki/jasmine/jasmine.js:2479:5)
    at jasmine.Queue.onComplete ($:/plugins/tiddlywiki/jasmine/jasmine.js:2523:10)
    at jasmine.Queue.next_ ($:/plugins/tiddlywiki/jasmine/jasmine.js:2107:14)
PS D:\git\tiddly\tiddlywiki\TiddlyWiki5> tiddlywiki .\editions\test\
WARNING: Filter modifier has a deprecated regexp operand /JoeBloggs/
WARNING: Filter modifier has a deprecated regexp operand /Jo/
WARNING: Filter modifier has a deprecated regexp operand /JoeBloggs/
WARNING: Filter modifier has a deprecated regexp operand /Jo/
$:/plugins/tiddlywiki/jasmine/reporter.js:191
      this.print_(stringValue);
           ^

TypeError: this.print_ is not a function
    at jasmineNode.TerminalVerboseReporter.printLine_ ($:/plugins/tiddlywiki/jasmine/reporter.js:191:12)
    at jasmineNode.TerminalVerboseReporter.reportRunnerResults ($:/plugins/tiddlywiki/jasmine/reporter.js:224:14)
    at jasmine.MultiReporter.reportRunnerResults ($:/plugins/tiddlywiki/jasmine/jasmine.js:1789:39)
    at jasmine.Runner.finishCallback ($:/plugins/tiddlywiki/jasmine/jasmine.js:2161:21)
    at jasmine.Queue.onComplete ($:/plugins/tiddlywiki/jasmine/jasmine.js:2145:10)
    at jasmine.Queue.next_ ($:/plugins/tiddlywiki/jasmine/jasmine.js:2107:14)
    at onComplete ($:/plugins/tiddlywiki/jasmine/jasmine.js:2093:18)
    at jasmine.Suite.finish ($:/plugins/tiddlywiki/jasmine/jasmine.js:2479:5)
    at jasmine.Queue.onComplete ($:/plugins/tiddlywiki/jasmine/jasmine.js:2523:10)
    at jasmine.Queue.next_ ($:/plugins/tiddlywiki/jasmine/jasmine.js:2107:14)
```

**Comment by Jermolene** [comment]
It would be good to get 5.1.22 out to resolve this. In the meantime can you use an older version of Node?

**Comment by pmario** [comment]
uups ... Did run with latest master so no jasmine error ... but many "test - errors". Will have a closer look

Did run with `tiddlywiki editions/test ..` instead of `node tiddlywiki.js .... ` so partly my fault :)
