### ISSUE TITLE
[BUG] Certain data folders access wiki method too early

### ISSUE THREAD

**Issue by Arlen22** [Jermolene/TiddlyWiki5#4587]
When running a data folder directly with Node or in TiddlyServer I get a rather strange error that seems to involve a new feature added in 5.1.22. This is with TiddlyWiki v5.1.22 and Node v12.14.1. Actually I'm on master right now, but I was already getting the error in the prerelease. I'm still digging, but it appears that a tiddler change event is being fired before the wiki object is fully initialized. 

```plain
$:/core/modules/startup/plugins.js:32
                                requiresReload = $tw.wiki.doesPluginRequireReload(title);
                                                          ^

TypeError: $tw.wiki.doesPluginRequireReload is not a function
    at $:/core/modules/startup/plugins.js:32:31
    at Object.$tw.utils.each (/Users/arlen/Desktop/GitHub/tiddlywiki-production-new/TiddlyWiki5-Jermolene/boot/boot.js:126:12)
    at Function.<anonymous> ($:/core/modules/startup/plugins.js:30:13)
    at $tw.Wiki.exports.dispatchEvent ($:/core/modules/wiki.js:133:13)
    at $:/core/modules/wiki.js:166:10
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
```
Adding the line `console.log(changes)` at the beginning of the change handler gives this output.

```plain
[Object: null prototype] {
  '$:/StoryList': [Object: null prototype] { modified: true }
}
```
Adding console.log($tw.wiki) gives this.

```plain
{
  addIndexer: [Function],
  getIndexer: [Function],
  addTiddler: [Function],
  deleteTiddler: [Function],
  getTiddler: [Function],
  allTitles: [Function],
  each: [Function] { byField: [Function], byTag: [Function] },
  allShadowTitles: [Function],
  eachShadow: [Function] { byField: [Function], byTag: [Function] },
  eachTiddlerPlusShadows: [Function] { byField: [Function], byTag: [Function] },
  eachShadowPlusTiddlers: [Function] { byField: [Function], byTag: [Function] },
  tiddlerExists: [Function],
  isShadowTiddler: [Function],
  getShadowSource: [Function],
  getPluginTypes: [Function],
  readPluginInfo: [Function],
  getPluginInfo: [Function],
  registerPluginTiddlers: [Function],
  unregisterPluginTiddlers: [Function],
  unpackPluginTiddlers: [Function],
  caches: [Object: null prototype] {},
  globalCache: [Object: null prototype] {},
  changedTiddlers: [Object: null prototype] {},
  changeCount: [Object: null prototype] { '$:/StoryList': 1 },
  eventListeners: {
    change: [ [Function], [Function], [Function], [Function], [Function] ],
    lazyLoad: [ [Function] ]
  },
  eventsTriggered: false
}
```

**Comment by Arlen22** [comment]
Here is the stack trace from the addTiddler call that triggers the event.

```plain
Adding $:/StoryList Error
    at $tw.Wiki.addTiddler ($:/boot/boot.js:1079:29)
    at openStartupTiddlers ($:/core/modules/startup/story.js:151:11)
    at Object.exports.startup ($:/core/modules/startup/story.js:39:2)
    at Object.$tw.boot.executeNextStartupTask ($:/boot/boot.js:2391:10)
    at Object.$tw.boot.executeNextStartupTask ($:/boot/boot.js:2395:21)
    at Object.$tw.boot.executeNextStartupTask ($:/boot/boot.js:2395:21)
    at Object.$tw.boot.executeNextStartupTask ($:/boot/boot.js:2395:21)
    at Object.$tw.boot.executeNextStartupTask ($:/boot/boot.js:2395:21)
    at Object.$tw.boot.executeNextStartupTask ($:/boot/boot.js:2395:21)
    at Object.$tw.boot.startup ($:/boot/boot.js:2348:11)
```

**Comment by Arlen22** [comment]
But load-modules should have taken care of adding the missing method, so I'm still digging.

**Comment by Arlen22** [comment]
I think I found the problem. It was a plugin that I had in the data folder. I thought so, but I didn't find it at first. The key was `$tw.wiki.shadowSource`
