### ISSUE TITLE
[BUG] TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by Heernis** [Jermolene/TiddlyWiki5#4786]
Using the `node tiddlywiki.js mynewwiki --listen` or `node tiddlywiki.js mynewwiki --server` leads to this error:

```
$:/core/modules/server/authenticators/header.js:17
	this.header = server.get("authenticated-user-header").toLowerCase();
	                                                     ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at new HeaderAuthenticator ($:/core/modules/server/authenticators/header.js:17:55)
    at Server.addAuthenticator ($:/core/modules/server/server.js:105:22)
    at $:/core/modules/server/server.js:59:8
    at /home/henuk/src/tiddlywiki/boot/boot.js:846:3
    at Object.$tw.utils.each (/home/henuk/src/tiddlywiki/boot/boot.js:135:12)
    at Object.$tw.modules.forEachModuleOfType (/home/henuk/src/tiddlywiki/boot/boot.js:845:12)
    at new Server ($:/core/modules/server/server.js:57:14)
    at Command.execute ($:/core/modules/commands/listen.js:37:16)
    at Commander.executeNextCommand ($:/core/modules/commander.js:107:14)
    at Commander.execute ($:/core/modules/commander.js:64:7)

```
https://github.com/Jermolene/TiddlyWiki5/blob/84b6a8529375d008cbf284fd496cda9c6d9ad714/core/modules/server/authenticators/header.js#L17

Removing `.toLowerCase()` of this line solved it.

```
node  v14.5.0
branch: master
```

**Comment by saqimtiaz** [comment]
This was introduced in #4780

**Comment by saqimtiaz** [comment]
@Jermolene note that `master` is currently broken as a result of this.
