### ISSUE TITLE
[BUG] NodeJS Error executing boot module $:/plugins/tiddlywiki/filesystem/filesystemadaptor.js

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#5901]
**Describe the bug**

Error executing boot module $:/plugins/tiddlywiki/filesystem/filesystemadaptor.js: {}

$:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:116
				$tw.utils.cleanupTiddlerFiles(options,function,cleanupTiddlerCallback);
				                                              ^

SyntaxError: Unexpected token ','
    at new Script (vm.js:101:7)
    at createScript (vm.js:262:10)
    at Object.runInNewContext (vm.js:303:10)
    at Object.$tw.utils.evalSandboxed (/Applications/TiddlyGit.app/Contents/Resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:546:5)
    at Object.$tw.modules.execute (/Applications/TiddlyGit.app/Contents/Resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:824:15)
    at /Applications/TiddlyGit.app/Contents/Resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:864:30
    at Object.$tw.utils.each (/Applications/TiddlyGit.app/Contents/Resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:135:12)
    at Object.$tw.modules.forEachModuleOfType (/Applications/TiddlyGit.app/Contents/Resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:863:12)
    at Object.exports.startup ($:/core/modules/startup.js:117:14)
    at Object.$tw.boot.executeNextStartupTask (/Applications/TiddlyGit.app/Contents/Resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:2464:10)

**To Reproduce**
1. Start latest(0720) nodejs wiki

**Expected behavior**

This function should not error

**Screenshots**

TiddlyGit (darwin)
Version v0.4.1-a16.

Electron Version: 14.0.0-beta.12
Node Version: 14.17.0
Chromium Version: 93.0.4557.4

**Additional context**

I use latest dev channel in my tiddlygit.

**Comment by linonetwo** [comment]
Oh, my fault, I was using my modified version.

**Comment by Jermolene** [comment]
No problem @linonetwo – I've often found that systematically writing down a bug report is often enough to trigger my brain to suddenly see what's actually going on.
