### ISSUE TITLE
[BUG] $:/core/modules/utils/fakedom.js:276

### ISSUE THREAD

**Issue by xtban** [Jermolene/TiddlyWiki5#7591]
### Describe the bug

i cannot login this morning 

### TiddlyWiki Configuration

- Version [e.g. v5.1.24]
- Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]
- Plugins installed [e.g. Freelinks, TiddlyMap]

### Additional context

$ tiddlywiki mynote --listen
syncer-server-filesystem: Dispatching 'save' task: $:/StoryList
Serving on http://127.0.0.1:8080
(press ctrl-C to exit)
$:/core/modules/utils/fakedom.js:276
                        return b.join("");
                                 ^

RangeError: Invalid string length
    at Array.join (<anonymous>)
    at TW_Element.get ($:/core/modules/utils/fakedom.js:276:13)
    at $:/core/modules/utils/fakedom.js:274:17
    at $tw.utils.each ($:/boot/boot.js:146:12)
    at TW_Element.get ($:/core/modules/utils/fakedom.js:273:14)
    at exports.renderTiddler ($:/core/modules/wiki.js:1235:144)
    at exports.handler ($:/core/modules/server/routes/get-index.js:22:24)
    at Server.requestHandler ($:/core/modules/server/server.js:300:9)
    at Server.emit (node:events:513:28)
    at parserOnIncoming (node:_http_server:1072:12)

Node.js v18.15.0

**Comment by xtban** [comment]
i may know why , i add the video as a tiddler ,and then it report wrong  . 

the video length exceed Max value

**Comment by pmario** [comment]
Since you have a node.js wiki, it should be possible to remove the "offending" video tiddler in the directory structure of the wiki. Then restarting the server should fix it.

**Comment by saqimtiaz** [comment]
Fixed in #9341
